[info]
# адрес сервера (по умолчанию server = 127.0.0.1)
server = "127.0.0.1"

# логин администратора
login = "***"

# Пароль администратора
password = "***"

# имя домена (по умолчанию @testdomain)
domain_name = "@testdomain"

# название файла со списком пользователей, которым необходимо добавить подпись
user_list = "userlist.xlsx"

# применить SIP пароль (да - 1, нет - 0)
# ВНИМАНИЕ! ЕСЛИ SIP В ПОЛОЖЕНИИ 1 ПЕРЕМЕННЫЕ УКАЗАННЫЕ НИЖЕ НЕ РАБОТАЮТ!
sip = 0

# пароль для замены (если нужно формировать рандом, то прописать "none"; пароль всегде прописывать в кавычках "")
new_password = "1"

# вкл/выкл пароль (вкл - 1, выкл - 0, не менять значение - 2)
pass_on = 1

# нужно ли менять пароль (да - 1, нет - 0)
change_pass = 1